name: CI Build
env:
  main_project_module: app
  playstore_name: GMSPhixit

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: echo "DISABLE_ANALYTICS=true" >> $GITHUB_ENV

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Decode google-services.json from secret
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > ${{ env.main_project_module }}/google-services.json

      - name: Setup Gradle Cache (dependencies and wrapper)
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
            gradle-

      - name: Generate Gradle Wrapper if missing
        run: |
          if [ ! -f ./gradlew ]; then
            gradle wrapper
          fi

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Setup Android SDK cmdline tools in home directory
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Set Android SDK env variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Set SDK directory in local.properties
        run: echo "sdk.dir=$HOME/android-sdk" > local.properties

      - name: Decode signing keystore file
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ./keystore.jks

      - name: Set signing environment variables
        run: |
          echo "SIGNING_KEY=$(pwd)/keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }}" >> $GITHUB_ENV
      
      - name: Build APKs and AAB
        run: ./gradlew assembleDebug assembleRelease bundleRelease

      - name: Zipalign and Sign Debug APK
        run: |
          chmod -R 0755 $HOME/android-sdk
          DEBUG_APK_PATH=$(find ${{ env.main_project_module }}/build/outputs/apk/debug -name "*-debug.apk" -print -quit)
          SIGNED_APK_PATH="${{ env.main_project_module }}/build/outputs/apk/debug/signed-${{ env.playstore_name }}-debug.apk"

          $HOME/android-sdk/build-tools/33.0.2/zipalign -v -p 4 \
            "$DEBUG_APK_PATH" \
            "$SIGNED_APK_PATH"

          $HOME/android-sdk/build-tools/33.0.2/apksigner sign \
            --ks ${{ github.workspace }}/keystore.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEYSTORE_PASS }} \
            --v1-signing-enabled true \
            --v2-signing-enabled false \
            --v3-signing-enabled true \
            --v4-signing-enabled false \
            "$SIGNED_APK_PATH"

          mv "$SIGNED_APK_PATH" ${{ env.main_project_module }}/build/outputs/apk/debug/${{ env.playstore_name }}-debug.apk

      - name: Zipalign and Sign Release APK
        run: |
          RELEASE_APK_PATH=$(find ${{ env.main_project_module }}/build/outputs/apk/release -name "*-release.apk" -print -quit)
          SIGNED_APK_PATH="${{ env.main_project_module }}/build/outputs/apk/release/signed-${{ env.playstore_name }}-release.apk"

          $HOME/android-sdk/build-tools/33.0.2/zipalign -v -p 4 \
            "$RELEASE_APK_PATH" \
            "$SIGNED_APK_PATH"

          $HOME/android-sdk/build-tools/33.0.2/apksigner sign \
            --ks ${{ github.workspace }}/keystore.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEYSTORE_PASS }} \
            --v1-signing-enabled true \
            --v2-signing-enabled false \
            --v3-signing-enabled true \
            --v4-signing-enabled false \
            "$SIGNED_APK_PATH"

          mv "$SIGNED_APK_PATH" ${{ env.main_project_module }}/build/outputs/apk/release/${{ env.playstore_name }}-release.apk

      - name: Sign and Rename Release AAB
        run: |
          RELEASE_AAB_PATH=$(find ${{ env.main_project_module }}/build/outputs/bundle/release -name "*-release.aab" -print -quit)
          $HOME/android-sdk/build-tools/33.0.2/apksigner sign \
          --ks ${{ github.workspace }}/keystore.jks \
          --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEYSTORE_PASS }} \
          --v1-signing-enabled true \
          --v2-signing-enabled false \
          --v3-signing-enabled true \
          --v4-signing-enabled false \
          "$RELEASE_AAB_PATH"
          
          mv "$RELEASE_AAB_PATH" ${{ env.main_project_module }}/build/outputs/bundle/release/${{ env.playstore_name }}-release.aab
      
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK Debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/${{ env.playstore_name }}-debug.apk

      - name: Upload Signed APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK Release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/${{ env.playstore_name }}-release.apk

      - name: Upload Signed AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - AAB Release
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/${{ env.playstore_name }}-release.aab
